ManagingEmployeVacations-PLayer/Controllers/VacationTypeController.cs
using AutoMapper;
using ManagingEmployeVacations_Bl.Repositorey;
using ManagingEmployeVacations_Dal.Entites;
using ManagingEmployeVacations_Dal.InterFaces;
using ManagingEmployeVacations_PLayer.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ManagingEmployeVacations_PLayer.Controllers
{
    public class VacationTypeController : Controller
    {
        private readonly IRepository<VacationType> _RepoVacationType;
        private readonly IMapper _Mapper;

        public VacationTypeController(IRepository<VacationType> _repoVacationType, IMapper map)
        {
            _RepoVacationType = _repoVacationType;
            _Mapper = map;
        }
        public IActionResult Index()
        {
            var Data = _RepoVacationType.GetAll().ToList();
            var DataVM = _Mapper.Map<IEnumerable<VacationTypeVm>>(Data);
            return View(DataVM);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(VacationTypeVm model)
        {
            if (ModelState.IsValid)
            {
                var VacationCreate = _Mapper.Map<VacationTypeVm, VacationType>(model);
                _RepoVacationType.Create(VacationCreate);
                return RedirectToAction(nameof(Index));
            }
            return View(model);

        }



        [HttpGet]
        public IActionResult Delete(int id, string NameView="Delete")
        {
   
                var VacationType = _RepoVacationType.GetById(id);
            var VacationTypeVm=_Mapper.Map<VacationTypeVm>(VacationType);

            return View(NameView, VacationTypeVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(VacationTypeVm Model)
        {

            if (ModelState.IsValid)
            {
                
                var VacationType = _Mapper.Map<VacationType>(Model);
                _RepoVacationType.DeleteEntity(VacationType);
                return RedirectToAction(nameof(Index));
            }
            return View(Model);
        }

        #region Update
        [HttpGet]
        public IActionResult update(int id)
        {
            return Delete(id, "Update");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult update(VacationTypeVm model)
        {
            if (ModelState.IsValid)
            {
                var VacationTypeCreate = _Mapper.Map<VacationTypeVm, VacationType>(model);
                _RepoVacationType.UpdateEntity(VacationTypeCreate);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        } 
        #endregion



    }
}

ManagingEmployeVacations-PLayer/Views/VacationType/Create.cshtml
@model VacationTypeVm


<div class="container p-4">




    <form asp-action="Create" method="post" asp-controller="VacationType">

        <div asp-validation-summary="All" class="alert"></div>
        <div class="form-group" hidden>
            <input class="form-control" asp-for="@Model.Id">
        </div>


        <div class="form-group">
            <label for="Name">Name</label>
            <input class="form-control" asp-for="Name">
            <span asp-validation-for="Name"></span>
        </div>



        <div class="form-group">
            <label for="Background_Color">Background_Color</label>
            <input class="form-control p-0"  type="color" asp-for="Background_Color">
        </div>

        <div class="form-group">
            <label for="NumberDays">NumberDays</label>
            <input class="form-control" asp-for="NumberDays">
            <span asp-validation-for="NumberDays"></span>
        </div>



        <button class="btn btn-success" type="submit">Create</button>
        <a class ="btn btn-danger" asp-action="Index">Back </a>
    </form>

</div>

ManagingEmployeVacations-PLayer/Views/VacationType/Delete.cshtml
@model VacationTypeVm

<div class="container p-5">


    <form asp-action="Delete" method="post" asp-controller="VacationType">
        <div asp-validation-summary="All" class="alert"></div>
        <div class="form-group" hidden>
            <label for="id">Name</label>
            <input class="form-control" asp-for="Id"  hidden>
        </div>


        <div class="form-group">
            <label for="Name">Name</label>
            <input class="form-control" asp-for="Name" readonly>
            <span asp-validation-for="Name"></span>
        </div>

        <div class="form-group">
            <label for="Background_Color">Background_Color</label>
            <input class="form-control p-0" type="color" asp-for="Background_Color" readonly>
        </div>


        <div class="form-group">
            <label for="NumberDays">NumberDays</label>
            <input class="form-control" asp-for="NumberDays" readonly>
            <span asp-validation-for="NumberDays"></span>
        </div>






        <button class="btn btn-success" type="submit">Delete</button>
        <button class="btn btn-danger" asp-action="Index">Back </button>



    </form>
</div>

ManagingEmployeVacations-PLayer/Views/VacationType/Index.cshtml
@model IEnumerable<VacationTypeVm>
@{
    ViewData["Title"] = "Vacation Type";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4>Departments</h4>

            <p>
                <a asp-action="Create" class="btn btn-info">Create New</a>
            </p>
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Background_Color)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NumberDays)
                        </th>

                        <th>Events</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>

                            <td style="background-color:@item.Background_Color;">
                                @Html.DisplayFor(modelItem => item.Background_Color)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NumberDays)
                            </td>
                            <td>
                                <a asp-action="Update" class="btn btn-primary" asp-route-id="@item.Id">Update</a>
                                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

ManagingEmployeVacations-PLayer/Views/VacationType/Update.cshtml
@model VacationTypeVm


<div class="container p-4">




    <form asp-action="Update" method="post" asp-controller="VacationType">
        <div asp-validation-summary="All" class="alert"></div>
        <div class="form-group" hidden>
            <input class="form-control" asp-for="@Model.Id">
        </div>


        <div class="form-group">
            <label for="Name">Name</label>
            <input class="form-control" asp-for="Name">
            <span asp-validation-for="Name"></span>
        </div>


        <div class="form-group">
            <label for="Background_Color">Background_Color</label>
            <input class="form-control p-0" type="color" asp-for="Background_Color" readonly>
        </div>






        <div class="form-group">
            <label for="NumberDays">NumberDays</label>
            <input class="form-control" asp-for="NumberDays">
            <span asp-validation-for="NumberDays"></span>
        </div>



        <button class="btn btn-success" type="submit">
            Update
        </button>
        <a class="btn btn-danger" asp-action="Index">Back </a>
    </form>

</div>